-- =============================================
-- Airbnb Listings Table Schema
-- =============================================

DROP TABLE IF EXISTS airbnb_listings;

CREATE TABLE airbnb_listings (

id BIGINT,
host_id	BIGINT,
room_type TEXT,
property_type TEXT,
price	NUMERIC(10,2),
accommodates  INTEGER,
bedrooms	INTEGER,
beds	INTEGER,
bathrooms_text	TEXT,
minimum_nights	INTEGER,
maximum_nights	INTEGER,
occupancy_rate	DOUBLE PRECISION,
estimated_occupancy_l365d	INTEGER,
estimated_revenue_l365d	NUMERIC(10,2),
number_of_reviews 	INTEGER,
review_scores_rating   DOUBLE PRECISION,
review_scores_accuracy  DOUBLE PRECISION,
review_scores_cleanliness DOUBLE PRECISION,
review_scores_checkin DOUBLE PRECISION,	
review_scores_communication	DOUBLE PRECISION,
review_scores_location  DOUBLE PRECISION,
review_scores_value	  DOUBLE PRECISION,
reviews_per_month	  DOUBLE PRECISION,
availability_30  INTEGER,	
availability_60	INTEGER,
availability_90	INTEGER,
availability_365     INTEGER,
latitude	DOUBLE PRECISION,
longitude	  DOUBLE PRECISION,
host_since	  DATE,
first_review    DATE,	
last_review   DATE,	
name	TEXT,
description   TEXT,
amenities      TEXT,
instant_bookable    BOOLEAN,
license	TEXT,
picture_url     TEXT,	
host_url	  TEXT,
host_response_time	TEXT,
host_response_rate	NUMERIC(5,2),
host_acceptance_rate   NUMERIC(5,2),	
host_is_superhost    BOOLEAN,
host_listings_count	INTEGER,
host_total_listings_count   INTEGER,
host_verifications	TEXT,
host_has_profile_pic	 BOOLEAN,
host_identity_verified	BOOLEAN,
neighbourhood_cleansed   TEXT,
bathrooms   DOUBLE PRECISION,	
minimum_minimum_nights    INTEGER,
maximum_minimum_nights	 INTEGER,
minimum_maximum_nights       INTEGER,
maximum_maximum_nights     INTEGER,
minimum_nights_avg_ntm    NUMERIC(10,2),
maximum_nights_avg_ntm    NUMERIC(10,2),
has_availability	BOOLEAN,
calendar_last_scraped	DATE,
number_of_reviews_ltm   INTEGER,	
number_of_reviews_l30d   INTEGER,	
availability_eoy	INTEGER,
number_of_reviews_ly   INTEGER,
);